pipeline {
    agent {
        kubernetes{
            label 'agent'
        }
    }
    triggers { pollSCM('* * * * *') }
    environment {
		DOCKERHUB_CREDENTIALS=credentials('35959979-9015-49e4-a7fb-916786b9572d')
	}
    stages {

	    stage('gitclone') {
            when {
                branch 'main'
            }
			steps {

			    echo " ============== gitclone =================="
				git 'https://github.com/alsxs/dip-net-ext2.git'
			}
		}

		stage('Build') {

			steps {
			    echo " ============== Build =================="
			    dir ('app') {
				    sh 'sudo docker build -t alsxs/nginx:app${BUILD_TIMESTAMP} .'
				}
			}
		}

		stage('Login + push') {

			steps {
			    echo " ============== Dockerhub login + push =================="
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
				sh 'sudo docker tag alsxs/nginx:app${BUILD_TIMESTAMP} alsxs/nginx:app${BUILD_TIMESTAMP}'
				sh 'sudo docker push alsxs/nginx:app${BUILD_TIMESTAMP}'
			}
		}

		stage('Kubernetes') {
            steps {
                echo " ============== Change app-deploy =================="
                withKubeConfig([credentialsId: '5959ed6b-7147-41c8-8f63-f157140d2c73',
                    serverUrl: 'https://127.0.0.1:6443',
                    contextName: 'kubernetes-admin@cluster.local',
                    clusterName: 'cluster.local',
                    namespace: 'default'
                    ]) {
                        sh 'kubectl delete deploy app-dip'
                        sh 'kubectl create deployment app-dip --image=alsxs/nginx:app${BUILD_TIMESTAMP} --port=80'
                        sh 'kubectl scale deployment app-dip --replicas 3'
                }
            }
        }
    }
}


